# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      # https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
    defer-datasource-initialization: false
  #---------------------
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    # Absolute path
    #    url: jdbc:h2:C:/projects/bootjava/restorant-voting/db/voting
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/restorant-voting/db/voting
    # Relative path form current dir
    #    url: jdbc:h2:./db/voting
    # Relative path from home
    #    url: jdbc:h2:~/voting
    #    tcp: jdbc:h2:tcp://localhost:9092/~/voting
    username: sa
    password:
    #https://marco.dev/spring-boot-h2-error
  h2.console.enabled: false

logging.level:
  root: warn
  net.osandman.votingforrestaurants: debug
  org.springframework.security.web.FilterChainProxy: debug

server.servlet:
    context-path: /api

springdoc.swagger-ui.path: /