spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
    defer-datasource-initialization: false
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2.console.enabled: false
  cache:
    cache-names: dishes, allDishes, restaurants, allRestaurants
    caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging.level:
  root: warn
  net.osandman.votingforrestaurants: debug
  org.springframework.security.web.FilterChainProxy: debug

server.servlet:
  context-path: /api

springdoc.swagger-ui.path: /